### ISSUE TITLE
Sync Translate Language for Dashboard and Profile

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#105]
Current the Dashboard and Profile not sync language 
select Spain in Dashboard but user go to Profile page -> Profile show EN language

**Comment by jatitoam** [comment]
@toanredweb can this be moved to QA?

**Comment by VanTrieuThanh** [comment]
![image](https://user-images.githubusercontent.com/44457418/186303081-cd7c9614-20d4-470d-be47-d0e2a75dd58a.png)
Still keep the language when uses click on Profile 
![image](https://user-images.githubusercontent.com/44457418/186303189-caff98ac-3f73-4143-b144-d4f8a502ed68.png)
