### ISSUE TITLE
Contents, Campaign - Filter Date range and filter campaign is override

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#111]
![Image](https://user-images.githubusercontent.com/44457418/187376853-1358a7a8-7917-4792-a68f-dd65f792765e.png)

**Comment by jatitoam** [comment]
@toanredweb I see a commit but not a PR?  can you please create the PR?

**Comment by jatitoam** [comment]
Found it https://github.com/aesirxio/dma-app/pull/113

**Comment by VanTrieuThanh** [comment]
It has work fine for me http://recordit.co/k9E0CVvB75
