### ISSUE TITLE
Change new font for DMA APP

### ISSUE THREAD

**Issue by PhuLy88** [aesirxio/dma-app#112]
- Double check again the overview APP (Font style, color, spacing etc)
- Change font SVN-Sofia to Open sans

**Comment by VanTrieuThanh** [comment]
it has change font-family 

![Image](https://user-images.githubusercontent.com/44457418/192422940-b6d4b2bb-2b7d-4b08-9aa1-ad9747638181.png)

![Image](https://user-images.githubusercontent.com/44457418/192423001-2d5c4aad-10f2-4217-99e4-0d686709d11d.png)
