### ISSUE TITLE
Thai translation

### ISSUE THREAD

**Issue by jatitoam** [aesirxio/dma-app#119]

**Comment by VanTrieuThanh** [comment]
it has work 

![Image](https://user-images.githubusercontent.com/44457418/192423104-7f00cef0-4f83-49e3-b72a-366f8be2ab54.png)

![Image](https://user-images.githubusercontent.com/44457418/192423133-4a0215e7-2c45-4354-89d3-7e509382a934.png)

**Comment by VanTrieuThanh** [comment]
I has got the translate not fine in calendar for AM, PM, 
![image](https://user-images.githubusercontent.com/44457418/192675541-3518f8b8-8e7d-4857-8a7a-57b6ebe14b95.png)
+ more
![image](https://user-images.githubusercontent.com/44457418/192675590-a894900a-80e1-4108-ab41-bec617f6b1f2.png)

**Comment by VanTrieuThanh** [comment]
has fixed 
![image](https://user-images.githubusercontent.com/44457418/193219318-438ca374-761e-46eb-8521-f189c646953b.png)
