### ISSUE TITLE
AesirX DAM Integration

### ISSUE THREAD

**Issue by lunguyenhat** [aesirxio/dma-app#122]
Create a Integrate component (DAMButton component) with:
- onClick: show the DAM dashboard
- OnClose: hide the DAM dashboard popup
- onSelect: return the url of asset.

**Comment by kakahuy113** [comment]
i had done my part please continue @GiaPhu811 please continue.
you can process by clone src from my github at here https://github.com/kakahuy113/dam-app i had write a doc in readme
And you can check my sample at https://github.com/kakahuy113/dma-app/commit/9eb1027137632d3bcee25a47ab6b75713dc87c6c too if you have any question feel free to ask

**Comment by kakahuy113** [comment]
https://github.com/aesirxio/dam-app/issues/63 and i had create my own issues if any question you can comment here @GiaPhu811 cc @lunguyenhat

**Comment by GiaPhu811** [comment]
add `REACT_APP_LICENSE=[Your DAM LICENSE on dam.aesirx.io]` in .env file to get items of dam

**Comment by VanTrieuThanh** [comment]
DAM 
![image](https://user-images.githubusercontent.com/44457418/212233513-fb8cc6dc-3d18-4e42-8ed0-0ea8391a2c16.png)
DMA 
![image](https://user-images.githubusercontent.com/44457418/212233552-2d89de94-e739-482d-9916-81732dd9137b.png)
