### ISSUE TITLE
Medium - Change the message when user connect success

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#123]
Medium

![Image](https://user-images.githubusercontent.com/44457418/192494573-e161e99e-8ac4-4b98-a564-0ad098c5fb44.png)

Twitter

![Image](https://user-images.githubusercontent.com/44457418/193204657-42be2cd9-46cb-4060-991b-181629170a03.png)

**Comment by toanredweb** [comment]
Hi @jatitoam , I connect to twitter but the api can't get the name and avatar. Can you help me check it?

**Comment by CongThuong** [comment]
> Hi @jatitoam , I connect to twitter but the api can't get the name and avatar. Can you help me check it?

How about the Medium when connecting successfully Em @toanredweb ?

**Comment by toanredweb** [comment]
Also  a @CongThuong

**Comment by CongThuong** [comment]
I updated the config in twitter's plugin, someone regenerated the token, that's why the old one cannot get account's info.

**Comment by toanredweb** [comment]
https://user-images.githubusercontent.com/70501609/209288728-d086b2a1-b426-4fb7-93f4-f90123e72a10.webm
 Wrong display message on Medium . Pls help me check again Anh @CongThuong

**Comment by CongThuong** [comment]
> 

https://user-images.githubusercontent.com/94885770/209294799-948fec7a-278a-428c-89b9-2c84078e20c3.mp4



I've checked and see the cahnnel's name is returned. Please check again Em @toanredweb

**Comment by toanredweb** [comment]
missing notification a @CongThuong 

![Image](https://user-images.githubusercontent.com/70501609/210296323-1f6a236e-8d14-4f35-b135-78ed19790586.png)

**Comment by NguyenBao10** [comment]
@CongThuong please double check e

**Comment by CongThuong** [comment]
please lemme know which branch or site you testing? Em @toanredweb

**Comment by CongThuong** [comment]
MR is merged on master. Demo-app works, please take a look Chi @VanTrieuThanh  Em @toanredweb

**Comment by huynhngocgiau** [comment]
Twitter: null a @CongThuong 
![message](https://user-images.githubusercontent.com/79819354/218400608-8d10f6a0-1eae-4b81-84ac-647fe9087359.png)

**Comment by CongThuong** [comment]
> Twitter: null a @CongThuong ![message](https://user-images.githubusercontent.com/79819354/218400608-8d10f6a0-1eae-4b81-84ac-647fe9087359.png)

Dev or master Em @huynhngocgiau ?

**Comment by CongThuong** [comment]
> Twitter: null a @CongThuong ![message](https://user-images.githubusercontent.com/79819354/218400608-8d10f6a0-1eae-4b81-84ac-647fe9087359.png)

Dev or master Em @huynhngocgiau ?

**Comment by huynhngocgiau** [comment]
> > Twitter: null a @CongThuong ![message](https://user-images.githubusercontent.com/79819354/218400608-8d10f6a0-1eae-4b81-84ac-647fe9087359.png)
> 
> Dev or master Em @huynhngocgiau ?

master @CongThuong

**Comment by CongThuong** [comment]
> 

Twitter channel is unavailable on master Em

**Comment by huynhngocgiau** [comment]
a @CongThuong 
![Screenshot from 2023-02-13 17-09-20](https://user-images.githubusercontent.com/79819354/218430176-49bda682-5978-4ede-a124-763d03524569.png)

**Comment by CongThuong** [comment]
> > 
> 
> Twitter channel is unavailable on master Em

sorry I'm wrong, this channel worked before on master

**Comment by huynhngocgiau** [comment]
worked
![image](https://user-images.githubusercontent.com/79819354/218721499-92acc134-be82-43e8-a08a-9925991fe46d.png)
