### ISSUE TITLE
Bug with easy logo setting

### ISSUE THREAD

**Issue by jatitoam** [aesirxio/dma-app#129]
From https://github.com/aesirxio/dma-app/issues/87#issuecomment-1263234658

The logo is not well kept

![Image](https://user-images.githubusercontent.com/1500978/193221197-d6f8fca6-d75e-4657-aad9-58922a911c7c.png)

**Comment by toanredweb** [comment]
help me check field member_logo e @nhatvippro

**Comment by nhatvippro** [comment]
it's fixed a, branch dev in local on ready @toanredweb

**Comment by toanredweb** [comment]
API return 'member_logo:null' e @nhatvippro 

![Image](https://user-images.githubusercontent.com/70501609/230527965-62015d17-79d2-447e-b3cc-aa05c1077939.png)
![Image](https://user-images.githubusercontent.com/70501609/230527966-120f2ed1-42bf-4a42-808e-b5e8b4946e4b.png)
