### ISSUE TITLE
Remove/Connect channel - Show message server error

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#135]
Remove channel
![Image](https://user-images.githubusercontent.com/44457418/194213165-8cf5f9c0-e082-4e1d-ac0c-dcbf0cd569ab.png)

Connect channel first time - cancel . Then reconnect it has show message server error

**Comment by GiaPhu811** [comment]
We have channelId and channelName in request but response said channelId and channelName are required. cc @jatitoam 
API : https://api.aesirx.io/index.php?webserviceClient=site&webserviceVersion=1.0.0&option=organisation_channel&task=removeChannel&api=hal
Below is payload and response:
![Image](https://user-images.githubusercontent.com/106291216/194259913-4c954579-8cc7-439f-93f9-6f3d34a5834b.png)

![Image](https://user-images.githubusercontent.com/106291216/194260037-63495dba-af43-4d82-8380-7d9a53ceb37b.png)

**Comment by NguyenBao10** [comment]
i see it's fine now, please check again e @VanTrieuThanh

**Comment by VanTrieuThanh** [comment]
at the endpoint livesite has working 
![image](https://user-images.githubusercontent.com/44457418/215981640-2463758d-b5ce-4025-9418-b8ce3d7f7925.png)
