### ISSUE TITLE
Connect channel - Joomla popup add the link for it

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#158]
Current the link not update so we can't add it 

![Image](https://user-images.githubusercontent.com/44457418/204477390-19ef723d-d20c-4eab-9c92-7b8cca9bede0.png)

Related with https://github.com/aesirxio/dma-app/issues/141

**Comment by toanredweb** [comment]
How about the link ? a @CongThuong  cc a @NguyenBao10

**Comment by VanTrieuThanh** [comment]
the document is not ready. The Document will guide get the  Grant Type, Client ID, Client Secret 
![image](https://user-images.githubusercontent.com/44457418/212032515-eb48939e-cea9-4c92-aff3-cb3de54c9feb.png)

**Comment by CongThuong** [comment]
yes Chị, We're using this values here temporately https://docs.google.com/spreadsheets/d/1c1ECCDlbuM7DpdTnqAJV33b297TP9WSbhcYZX3uIq54/edit#gid=0

**Comment by toanredweb** [comment]
There is currently no link document so I can't add it cc @VanTrieuThanh
