### ISSUE TITLE
DMA integration

### ISSUE THREAD

**Issue by trangiahuy031099** [aesirxio/dma-app#164]

**Comment by GiaPhu811** [comment]
@kakahuy113 please show alert or something to warn when missing title, description or error

**Comment by kakahuy113** [comment]
@GiaPhu811 please update test case for QA

**Comment by kakahuy113** [comment]
@GiaPhu811 also connect channel in DMA tab and that is post to social media

**Comment by VanTrieuThanh** [comment]
MCMS
![image](https://user-images.githubusercontent.com/44457418/212235530-6d190ef0-a7c2-47c8-804b-3b0224dc9d27.png)

**Comment by VanTrieuThanh** [comment]
run step for checking with MCMS
step1: Create 1 post of DMA integration at the demo mcms site
step 2: Go to the channel just post the item and check it has post success or no
step3: Go to the DMA with account (MCMS) and check the post just create has show on the list Content
