### ISSUE TITLE
Login app - Change the basic style

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#174]
on the dev site 
Compare with design DAM to clone about the style 
https://www.figma.com/file/m0VZCJPKKj8uGOfZReXMYR/AesirX-Platform?node-id=5290%3A29850&t=jdUBSTjC1zu0f0ws-0
Remember change text for each project 
![image](https://user-images.githubusercontent.com/44457418/210478940-f4fb8313-1db1-467b-8310-1bedc5e25953.png)

**Comment by VanTrieuThanh** [comment]
the login page not same design ![image](https://user-images.githubusercontent.com/44457418/212039656-fbd7b342-8da7-4194-bf74-424bb2cb4360.png)

**Comment by VanTrieuThanh** [comment]
The login layout not same design
![image](https://user-images.githubusercontent.com/44457418/216265610-960b732e-5d01-49fc-a875-64daee595cbb.png)

**Comment by huynhngocgiau** [comment]
the login page not same design
![image](https://user-images.githubusercontent.com/79819354/216306293-d9929cec-87d6-4e43-b79b-2f391aef87f0.png)
Design
![image](https://user-images.githubusercontent.com/79819354/216306376-51f06b4f-844b-492b-b297-bd844381543f.png)

**Comment by huynhngocgiau** [comment]
1. Border-bottom: #DEDEDE
![border-bottom](https://user-images.githubusercontent.com/79819354/218968971-194754e6-c29a-4612-b8e6-dd5f13bae208.png)
2. Change text "or" to "OR" and color: #8E8E8E
![changeText](https://user-images.githubusercontent.com/79819354/218972153-cc01d4ce-5a79-44ec-810d-689bdef4baf2.png)
3. Text color "Email", "Password", "*"
+ "Email", "Password": #000000;
+  "*": #C60202
4. Field border color "Email" and "Password"
+ border: 1px solid #D5D5D5
+ active: 1px solid #0A083B
![border](https://user-images.githubusercontent.com/79819354/218972707-f45d6039-a4e2-47d0-9b4d-9267ba050eb9.png)
5. Text color "Forgot password?": #3B7AB5
![forgot](https://user-images.githubusercontent.com/79819354/218977831-38276cb7-e36d-40e7-9359-d3285ed4afc6.png)
6. Uppercase "SIGN IN"
![image](https://user-images.githubusercontent.com/79819354/218979203-9bf4792e-0d0d-4559-a6e4-1095f2379d98.png)
Please check again a @toanredweb

**Comment by huynhngocgiau** [comment]
conflict a @toanredweb

**Comment by VanTrieuThanh** [comment]
The page login will remove field Username/Password but Sign in so the text and button Sign in will adjust a little bit
![image](https://user-images.githubusercontent.com/44457418/220266083-22b8d021-f7c4-4e6c-9454-fa4f345deaf2.png)

**Comment by huynhngocgiau** [comment]
has updated 
![Screenshot from 2023-02-21 14-02-44](https://user-images.githubusercontent.com/79819354/220272430-3940de30-4f4a-43d7-8f2e-372d669bf79f.png)
