### ISSUE TITLE
Window 10 - HP EliteBook - Chrome - Can't see text in dark mode

### ISSUE THREAD

**Issue by huynhngocgiau** [aesirxio/dma-app#176]
When using in dark mode I can't see the text
![textcolor](https://user-images.githubusercontent.com/79819354/210479346-511d9e7e-429a-439f-8f7c-b43dd401792a.png)

**Comment by VanTrieuThanh** [comment]
has update ![image](https://user-images.githubusercontent.com/44457418/212030166-2350eddd-937a-4605-831d-9c2339801a76.png)
