### ISSUE TITLE
Message status - Change style 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#179]
![image](https://user-images.githubusercontent.com/44457418/210485494-f5d34c3a-19ff-4d1f-bc32-47ae0a579f15.png)
Design at 
https://www.figma.com/file/m0VZCJPKKj8uGOfZReXMYR/AesirX-Platform?node-id=552%3A1816&t=jdUBSTjC1zu0f0ws-0

**Comment by GiaPhu811** [comment]
We have version 2 so i will close this one #212
