### ISSUE TITLE
DAM Integration - Can't create/upload/select/drop files 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#188]
![image](https://user-images.githubusercontent.com/44457418/210923138-4b919214-3db1-4d69-ae69-93321032f895.png)

**Comment by NguyenBao10** [comment]
We are fixing API

**Comment by NguyenBao10** [comment]
a @hoang-tran-redweb fixed, please check again e @VanTrieuThanh

**Comment by VanTrieuThanh** [comment]
Upload, Drop and Select file not fine on the local 
![image](https://user-images.githubusercontent.com/44457418/212027473-ab07df59-f4c2-47d2-b7a8-95cedf6266a0.png)

**Comment by VanTrieuThanh** [comment]
upload file not working 
![image](https://user-images.githubusercontent.com/44457418/215708628-74d2bd6d-7c63-436b-89a6-ba814ce0fa47.png)
Can delete the text 
![image](https://user-images.githubusercontent.com/44457418/215708730-7c08c870-a629-4193-95b2-8b599d3fb988.png)
