### ISSUE TITLE
Delete item not working 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#189]
http://recordit.co/758baXnz67

**Comment by NguyenBao10** [comment]
We are fixing API

**Comment by GiaPhu811** [comment]
It's work again chị @VanTrieuThanh

**Comment by VuCongThuong** [comment]
This issue is fixed, please check again Chị @VanTrieuThanh

**Comment by VanTrieuThanh** [comment]
I will check when connect channel to delete post. The Project, Campaign has fine for me
