### ISSUE TITLE
Campaign - Remove the content change when user click on the Save button

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#190]
- Click on the item need edit the Project field is missing 
![image](https://user-images.githubusercontent.com/44457418/210923890-012153c0-7793-4317-999c-6f8d2b979d0d.png)
- Select again and change some where 
![image](https://user-images.githubusercontent.com/44457418/210923974-a7b6234b-7495-47f2-b8d6-d9845072dc73.png)
- Click on the Save button the popup remove the content has change in popup
![image](https://user-images.githubusercontent.com/44457418/210924086-948a8b6c-0143-4c9a-a53d-d65799861c47.png)

**Comment by VuCongThuong** [comment]
It's fixed, please take a look Chi @VanTrieuThanh  Em @GiaPhu811

**Comment by VanTrieuThanh** [comment]
has fixed ![image](https://user-images.githubusercontent.com/44457418/212022357-d4d5c715-d293-4ebc-aa71-63b780890f71.png)

**Comment by VanTrieuThanh** [comment]
has update on the demo site 
![image](https://user-images.githubusercontent.com/44457418/212634628-f7048ebb-08d9-4b32-87a2-db80aec963c9.png)
