### ISSUE TITLE
Campaign - Filter working incorrect 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#191]
Range date 
Select the range date from Jan 5 to Feb 4 
![image](https://user-images.githubusercontent.com/44457418/210924770-4ca29956-7b9b-4620-bbe6-89118d290380.png)
when click apply it has show on the test item 
![image](https://user-images.githubusercontent.com/44457418/210924869-b0e4291f-89c4-446a-86eb-73cea548046c.png)
Filter with project - look like the project has remove in campaign item so it working incorrect 
![image](https://user-images.githubusercontent.com/44457418/210924989-5a7b9e1b-8cc1-46ef-b5fa-153975c6e6bd.png)

**Comment by GiaPhu811** [comment]
@CongThuong API return wrong. Please help me check a @NguyenBao10

**Comment by anhtuan2588** [comment]
@VanTrieuThanh please check this task again (fixed)

**Comment by VanTrieuThanh** [comment]
Create item select 02-02 but in network show 01-02
![image](https://user-images.githubusercontent.com/44457418/216296224-5d46d53e-787c-464e-ada4-109123794935.png)
![image](https://user-images.githubusercontent.com/44457418/216296274-39b170d9-0a5e-48be-a5d4-70316d0df278.png)

**Comment by anhtuan2588** [comment]
@VanTrieuThanh with the error showing the time, it's an error from the front-end, I already asked @GiaPhu811 , please ask him and create this task for the front-end

**Comment by VanTrieuThanh** [comment]
I will create the new task for FE
With the task I try on the endpoint live with license 3da8d03684b9432c99ccd8bdd9afd940 for acc qa@test.r-digital.tech/qa@test.r-digital.tech. Not working fine 
http://recordit.co/Wr5SyoF8Xj

**Comment by VanTrieuThanh** [comment]
I'll check after the app has fixed the Something wrong
