### ISSUE TITLE
Create Post - the page is loading overtime

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#192]
![image](https://user-images.githubusercontent.com/44457418/210926646-dc55a6d5-f306-42e7-bfb3-1ff45ee90823.png)
User click on the Create post - web page loading overtime
![image](https://user-images.githubusercontent.com/44457418/210926537-0cb11ed8-35e5-4777-8b81-48fe08376d8c.png)

**Comment by NguyenBao10** [comment]
API's error, we will update here after it's fixed @VanTrieuThanh @hongdtb41

**Comment by NguyenBao10** [comment]
it's fixed e @VanTrieuThanh

**Comment by VanTrieuThanh** [comment]
can't check because can't connect channel
