### ISSUE TITLE
Channel - Missing channel item 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#193]
![image](https://user-images.githubusercontent.com/44457418/210926790-6e421395-c064-4a2a-b994-cd9ea0bfe064.png)

**Comment by NguyenBao10** [comment]
a @anhtuan2588 fixed this, please check again e @VanTrieuThanh

**Comment by NguyenBao10** [comment]
there was an error in API

**Comment by VanTrieuThanh** [comment]
![image](https://user-images.githubusercontent.com/44457418/210995625-9d3d16a2-0f0e-41b8-90b8-a5d00066a5ab.png)
it fine for me on the demo site
