### ISSUE TITLE
[Avatar] show letter avatar when there is no image

### ISSUE THREAD

**Issue by hongdtb41** [aesirxio/dma-app#205]
On each demo sites ,  when the user is logged in, his letters avatar will display.

**Comment by lunguyenhat** [comment]
https://github.com/aesirxio/pim-app/pull/199

**Comment by VanTrieuThanh** [comment]
The first letter in name has add on the avatar when pull code and change SSO version 1.0.6
![image](https://user-images.githubusercontent.com/44457418/222670649-a3a9705c-888d-4e49-b7b5-f4672f310231.png)
