### ISSUE TITLE
Message status - Version 2

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#212]
![image](https://user-images.githubusercontent.com/44457418/212270824-6e4e5ef7-9141-4e18-b721-94744adef1f9.png)
Design at 
https://www.figma.com/file/m0VZCJPKKj8uGOfZReXMYR/AesirX-Platform?node-id=552%3A1816&t=h8aObSmTfUsu9fNt-0

**Comment by huynhngocgiau** [comment]
Warning
![image](https://user-images.githubusercontent.com/79819354/216299067-7970e704-dafe-4a78-9abb-17f3d0a026b1.png)
Error
![image](https://user-images.githubusercontent.com/79819354/216299120-587b18d4-0d5e-49a5-b381-7e536dbc243c.png)
Successful: worked

**Comment by huynhngocgiau** [comment]
Warning: wrong UI
![image](https://user-images.githubusercontent.com/79819354/216537161-ac827864-1a35-4706-80b3-cffc1b940a2d.png)
Error: work
![image](https://user-images.githubusercontent.com/79819354/216533439-45f26a0b-2ed9-4b96-9ae6-1838d91504e1.png)
