### ISSUE TITLE
Create /Edit project - Fix some bug on the demo site 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#214]
1 Create item - Not work when user click on the "Create project" button 
<img width="1410" alt="Screen Shot 2023-01-16 at 15 22 01" src="https://user-images.githubusercontent.com/44457418/212630596-efdf13f7-0a73-45e8-ae16-25fe5e833787.png">

2 Edit item - Don't show image when user add after create item 
Create success the item project but add image 
Click on the item to add the image 
Actual result: the image not show on the list and detail 
![image](https://user-images.githubusercontent.com/44457418/212630679-cb183f98-b341-4b67-8822-db69ae5e2642.png)

**Comment by toanredweb** [comment]
Pls wait for the release demo and check again chị @VanTrieuThanh

**Comment by VanTrieuThanh** [comment]
the issue 2 not working

**Comment by huynhngocgiau** [comment]
has updated
![image](https://user-images.githubusercontent.com/79819354/219340633-b121686e-cb6b-4ed3-ab8a-2c3f911cb0ee.png)
