### ISSUE TITLE
Message still show number, the image channel is error

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#218]
Check the message when user connect success and image channel 
![image](https://user-images.githubusercontent.com/44457418/212657914-f13699e4-7fd1-4b77-81b1-2c760c3623d4.png)

**Comment by huynhngocgiau** [comment]
has updated
![image](https://user-images.githubusercontent.com/79819354/218400865-50bcd409-99c3-4f6e-9005-bd0c0e5eac87.png)
