### ISSUE TITLE
Edit Post - Missing the Project, Campaign 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#219]
![image](https://user-images.githubusercontent.com/44457418/212660571-2511bb56-e32e-4940-b0f3-66b0c8b0dca5.png)

**Comment by thach-redweb** [comment]
API still working, pls check in FE @toanredweb

**Comment by VanTrieuThanh** [comment]
not update @toanredweb oi

**Comment by toanredweb** [comment]
API project, campaign, channel returns null . Pls check again a @thach-redweb

**Comment by toanredweb** [comment]
![Image](https://user-images.githubusercontent.com/70501609/216274031-6e05d3c1-2674-492b-b585-12078d55df00.png)

**Comment by thach-redweb** [comment]
fixed! @toanredweb pls check api on site dev01

**Comment by thach-redweb** [comment]
@toanredweb on Live also have data, please check !

![image](https://user-images.githubusercontent.com/117978085/216534364-e4cf0a2f-8be6-4310-a548-a217f227708d.png)

**Comment by huynhngocgiau** [comment]
worked
![image](https://user-images.githubusercontent.com/79819354/224298771-5d5f28f6-1671-437b-8fce-9aa51c6720fa.png)
