### ISSUE TITLE
Wrong color with design

### ISSUE THREAD

**Issue by huynhngocgiau** [aesirxio/dma-app#220]
Too much border color, background color are wrong with design. Please check again all page

**Comment by huynhngocgiau** [comment]
![login](https://user-images.githubusercontent.com/79819354/213110163-8449970a-292d-4d1a-8acb-fc2e397181e9.png)
![calendar](https://user-images.githubusercontent.com/79819354/213110275-539b933b-693b-45b0-8f3c-113e319cb0eb.png)

**Comment by huynhngocgiau** [comment]
Please check again a @toanredweb 
1. Add icon and change icon 
2. Style text "Schedule"
![image](https://user-images.githubusercontent.com/79819354/222699660-92ffffe6-8008-4088-9e0c-4d6200e8132e.png)

**Comment by huynhngocgiau** [comment]
Add icon for Today and change icon for Filter
![Screenshot from 2023-03-10 11-23-30](https://user-images.githubusercontent.com/79819354/224223141-1b49284d-109d-4325-9c00-64d076222163.png)

**Comment by toanredweb** [comment]
Today button is not a dropdown button e @huynhngocgiau

**Comment by huynhngocgiau** [comment]
has updated 
![image](https://user-images.githubusercontent.com/79819354/224240581-351ef82d-3de3-4a29-8e57-e001ad987d66.png)
