### ISSUE TITLE
Channels - Maintenance status

### ISSUE THREAD

**Issue by lunguyenhat** [aesirxio/dma-app#233]
One more status maintenance with published = 2 for non working channels

![Image](https://user-images.githubusercontent.com/2959010/216547994-f037ecd4-12dd-4e09-8595-4d7930f87d40.png)

**Comment by thaoredweb** [comment]
![image](https://user-images.githubusercontent.com/30283123/217478365-20b9a103-f637-4cff-9529-6dc13c00cc23.png)
It has been deployed
