### ISSUE TITLE
Create Project - Add message successful

### ISSUE THREAD

**Issue by huynhngocgiau** [aesirxio/dma-app#234]
https://user-images.githubusercontent.com/79819354/216549891-258a5e3c-5eae-4d3a-afca-c09fb85dba38.mp4

**Comment by VanTrieuThanh** [comment]
has update 
![image](https://user-images.githubusercontent.com/44457418/220591880-0f1d4ac5-f2ed-4a27-b7c5-124c8c61ef94.png)

**Comment by VanTrieuThanh** [comment]
has update 
![image](https://user-images.githubusercontent.com/44457418/220592152-a8068631-6844-4e8c-a91f-43684a98e02d.png)
