### ISSUE TITLE
Campaign - Filter Range date missing background 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#237]
![image](https://user-images.githubusercontent.com/44457418/216580757-aa18f7d1-b837-4129-b7e0-0cd72fb7f3ce.png)

**Comment by huynhngocgiau** [comment]
Missing text
![image](https://user-images.githubusercontent.com/79819354/223008368-a2b171f7-7b41-4fd4-9574-6ffde09ed676.png)
