### ISSUE TITLE
The color of message is difficult to read

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/dma-app#241]
![Image](https://user-images.githubusercontent.com/30283123/217767360-c670fd76-93da-4843-9095-12c67f5ce7ee.png)

**Comment by VanTrieuThanh** [comment]
![image](https://user-images.githubusercontent.com/44457418/223017008-6025244a-298b-4b37-b3f5-7cbf4128bc8b.png)
the color mesage has update
