### ISSUE TITLE
Can not update the start date

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/dma-app#244]
1. Launch the app
2. Go to Project, select an proejct to edit

Actual output:
Can not edit an project at start date 

![Image](https://user-images.githubusercontent.com/30283123/218051967-e4cdaa83-66d1-406a-a50f-4c1d2633fc20.png)

(FE+BE)

**Comment by toanredweb** [comment]
It working  cc chi @thaoredweb

**Comment by VanTrieuThanh** [comment]
The start date can edit
