### ISSUE TITLE
Hover affects are not same

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/dma-app#245]
I do click some elements on page. Hover effects are not same style

![Image](https://user-images.githubusercontent.com/30283123/218060208-820a0237-9638-49f6-8cf6-1d5893fa2b7d.png)

![Image](https://user-images.githubusercontent.com/30283123/218060399-ae9f1277-9bb9-4253-b507-39ebc4520421.png)

![Image](https://user-images.githubusercontent.com/30283123/218060498-68ea1adf-a28b-49d5-9811-eb3bb4fb7f1e.png)

![Image](https://user-images.githubusercontent.com/30283123/218060839-718b6992-93e5-4917-9512-641c40d0aded.png)

**Comment by huynhngocgiau** [comment]
has updated 
![image](https://user-images.githubusercontent.com/79819354/220283520-dff1ceeb-4851-4818-b5c9-98eaf61ac665.png)
