### ISSUE TITLE
ChatGPT plugin

### ISSUE THREAD

**Issue by lunguyenhat** [aesirxio/dma-app#246]
Integrate ChatGPT at Editor of content when post the content. User will ask the ChatGPT and copy the answer to Editor.

**Comment by VanTrieuThanh** [comment]
I check the login SSO not success @toanredweb help me check it again or assign BE to check
![image](https://user-images.githubusercontent.com/44457418/222635142-83feeabe-32d7-4477-b28f-a685a10c7240.png)
but I check PR=https://github.com/aesirxio/dma-app/pull/276 SSO has login success

**Comment by VanTrieuThanh** [comment]
change version SSO 1.0.6 and pull code then run app after add API key OPENAI in .env
![image](https://user-images.githubusercontent.com/44457418/222669450-11e7fa46-d384-4932-aeba-0f5123495b97.png)
