### ISSUE TITLE
Wrong UI - Channel - Connect Twitter - Message

### ISSUE THREAD

**Issue by huynhngocgiau** [aesirxio/dma-app#248]
Success 
Actual: wrong text color
![image](https://user-images.githubusercontent.com/79819354/218624357-cc88e6d7-a664-4260-945c-ee7674c339e3.png)

Warning
Actual: wrong content
![image](https://user-images.githubusercontent.com/79819354/218634775-d95ab605-83d4-4766-94c1-ae1a65b5f6df.png)

Design: 
![image](https://user-images.githubusercontent.com/79819354/218625421-8e711908-2096-4ecb-b62c-f9a32446e691.png)

**Comment by VanTrieuThanh** [comment]
Can't connect channel - BE is fixing
