### ISSUE TITLE
UI - Campaign, Content - Style the filter date

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#251]
Here is the design of filter day
![image](https://user-images.githubusercontent.com/44457418/219563016-2f4a3c16-a21a-4ef1-abf9-d3762279a5b0.png)
-> But I talk to Viet to custom it from plugin so it will be like this
(This from BI platform, please adapt for all) 
![image](https://user-images.githubusercontent.com/44457418/219563057-7256881d-e113-4db9-8d55-288bd5513cfa.png)

**Comment by vietredweb** [comment]
Please follow this e @toanredweb https://github.com/aesirxio/bi-app/pull/58/files

**Comment by VanTrieuThanh** [comment]
remove date, change icon, color text 
![image](https://user-images.githubusercontent.com/44457418/222069745-6bedd51e-7646-4334-a049-15c7e80593f6.png)
missing line / remove line 
![image](https://user-images.githubusercontent.com/44457418/222070066-b7e87669-fceb-4253-ac9f-7cf8019787cd.png)
Dark mode 
![image](https://user-images.githubusercontent.com/44457418/222070321-2a4c189d-b888-4c5c-bbc3-3443e547db70.png)

**Comment by VanTrieuThanh** [comment]
Dark mode - background select date not same design 
![image](https://user-images.githubusercontent.com/44457418/222112528-c4aae7de-cd6d-4d4a-aa3c-95e518d71eeb.png)
design 
![image](https://user-images.githubusercontent.com/44457418/222112917-153ceb2c-8769-4888-8d11-dc407001c387.png)
Decrease the spacing date to line bottom
![image](https://user-images.githubusercontent.com/44457418/222113422-a93717b1-57fc-464f-9548-8985523268b0.png)
Increase spacing between month and days in the week
![image](https://user-images.githubusercontent.com/44457418/222114571-dd78a0d2-84dd-4eac-8af3-fd2127eac7f2.png)

**Comment by huynhngocgiau** [comment]
Wrong color of text and icon 
![image](https://user-images.githubusercontent.com/79819354/223010585-10fc9e6f-32f5-4038-b185-67b9f0adf460.png)
