### ISSUE TITLE
Login - Remove Authentication Login

### ISSUE THREAD

**Issue by lunguyenhat** [aesirxio/dma-app#252]
https://github.com/aesirxio/dam-app/issues/215

**Comment by VanTrieuThanh** [comment]
check the login page has background 
![image](https://user-images.githubusercontent.com/44457418/220593492-a1475129-d5b1-4642-bc2b-0f614276fc73.png)

**Comment by VanTrieuThanh** [comment]
![Screenshot from 2023-02-23 18-13-02](https://user-images.githubusercontent.com/44457418/220890693-39e9e30f-f7e6-4fb8-b7de-ffb2abfc20c1.png)
it fine for me on the local

**Comment by VanTrieuThanh** [comment]
has fix with version SSO 1.0.6
![image](https://user-images.githubusercontent.com/44457418/222667682-ebadd31a-8e3a-409a-a95e-d1a27954d195.png)
