### ISSUE TITLE
Witdth of dropdown should be in unity

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/dma-app#270]
![Image](https://user-images.githubusercontent.com/30283123/220860145-9400dfd8-f959-44d6-85a4-a360fee3c0df.png)

![Image](https://user-images.githubusercontent.com/30283123/220860204-9e332444-01a1-4f0a-a0e9-3ad583c27717.png)
 Long has fixed twith the PR. Reference at
https://github.com/aesirxio/mcms-app/pull/82

**Comment by VanTrieuThanh** [comment]
has fix
![image](https://user-images.githubusercontent.com/44457418/222686920-f6bcb247-4bd6-4709-8526-9f28dd878670.png)
![image](https://user-images.githubusercontent.com/44457418/222686981-80e657f4-7505-4eea-9352-2bd2d143934e.png)
