### ISSUE TITLE
Pagination - Change UI same as design

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#277]
Project/Campaign/Content pagination should be same design 
Light mode https://www.figma.com/file/m0VZCJPKKj8uGOfZReXMYR/AesirX-Platform?node-id=4681%3A27775&t=AOBUU4VfdQKFplat-0
![Image](https://user-images.githubusercontent.com/44457418/222625549-2e3eec0b-66f3-4d7c-80ab-94cb730e9f9c.png)
Dark mode https://www.figma.com/file/m0VZCJPKKj8uGOfZReXMYR/AesirX-Platform?node-id=7729%3A44226&t=AOBUU4VfdQKFplat-0
![Image](https://user-images.githubusercontent.com/44457418/222625665-2c510d38-d536-4771-a27a-cc385c4b07a3.png)

**Comment by huynhngocgiau** [comment]
Dark mode
Wrong color text and icon
![image](https://user-images.githubusercontent.com/79819354/224889497-fd1e4626-6451-4cb4-87d9-7bbef0f45f5f.png)
Background: #1A2226
![image](https://user-images.githubusercontent.com/79819354/224889965-7a07097f-688b-4b6d-8d39-7629cd098348.png)
Add border to all
![image](https://user-images.githubusercontent.com/79819354/224891075-a3049e75-73d3-444d-94d4-d602e952578d.png)

**Comment by huynhngocgiau** [comment]
Background: #0F1314
![image](https://user-images.githubusercontent.com/79819354/225815417-ffe02f75-c8a5-41dc-ae71-7c24361d385f.png)

**Comment by VanTrieuThanh** [comment]
Light mode - color number
![image](https://user-images.githubusercontent.com/44457418/225866065-c9583e2e-1dad-4c7c-9891-9b3f99784e35.png)
