### ISSUE TITLE
Post - Icon "down" in filter date does not work when the user clicks 2 times

### ISSUE THREAD

**Issue by jatitoam** [aesirxio/dma-app#28]
1 Column field has hover when user click on icon "down” / Filter field has hover when user click on icon "down” 

=> It should be display hover color is same 

2 Icon "down" in filter date not work when user click 2 time

http://recordit.co/tlppr0klJQ

**Comment by jatitoam** [comment]
Ref #25

**Comment by thaoredweb** [comment]
It works to me now @jatitoam
