### ISSUE TITLE
UI - Not same design 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#287]
Campaign - Missing background
![image](https://user-images.githubusercontent.com/44457418/225570010-0d21b6fc-3252-4329-acde-b3c0996cc2bc.png)
List - the padding is large 
![image](https://user-images.githubusercontent.com/44457418/225571035-17ca18b7-a429-48d3-b464-1dc98f780397.png)
List - Missing background
![image](https://user-images.githubusercontent.com/44457418/225571629-7f531715-bc39-4346-a9eb-0f4ea69314f9.png)
Language - Missing background 
![image](https://user-images.githubusercontent.com/44457418/225572900-61837fce-e9ad-41a7-8f46-deee654b01f4.png)
Calendar - Hover 
![Screenshot from 2023-03-16 16-29-31](https://user-images.githubusercontent.com/44457418/225575200-e6afbdcb-620a-466e-bfe3-f4d9ec0e7e5a.png)

**Comment by huynhngocgiau** [comment]
![image](https://user-images.githubusercontent.com/79819354/226239537-2ff68b38-2ef7-4a9b-aa2a-10c03ded3946.png)

**Comment by VanTrieuThanh** [comment]
this one not update 
![image](https://user-images.githubusercontent.com/44457418/226792076-38930ad4-df7a-45b8-909b-ae1ba64a45a5.png)
