### ISSUE TITLE
Show a single alert on the profile page

### ISSUE THREAD

**Issue by jatitoam** [aesirxio/dma-app#33]
User clicks on the Profile 
Current result : it shows 2 messages

![Image](https://user-images.githubusercontent.com/1500978/173701933-d7599345-9530-4de3-920c-c5e6a4b6149c.png)

**Comment by jatitoam** [comment]
@toanredweb there is no PR for this one?

**Comment by jatitoam** [comment]
I don't see any PR here @toanredweb  so I'm reopening it

**Comment by VanTrieuThanh** [comment]
it has removed the alert 
![image](https://user-images.githubusercontent.com/44457418/203732983-dfb540d3-5599-4598-8a40-c1b9c5ca801e.png)
