### ISSUE TITLE
Web app does not work with the latest node version 16.15.1

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/dma-app#40]
Reproceduce:
- Install git
- Install node 16.15.1
- Run npm i then npm start
( Reference guide here https://dma.aesirx.io/install-guide/npm) 

 Actual output:
 The app does not work at local but it does not work

![Image](https://user-images.githubusercontent.com/30283123/175854567-21d1ea6b-bd1f-470e-831e-10dac49a53b5.png)

I got the same situation for node 14.17.3

**Comment by jatitoam** [comment]
There is something outdated in your environment.

Please try the following:

1. Make sure you're using the latest `develop` branch: `git pull origin develop`.
2. Delete your `node_modules` directory (fully).
3. `npm i`
4. `npm start`

**Comment by thaoredweb** [comment]
Nope @jatitoam We have clone a new site

**Comment by jatitoam** [comment]
Could you please record a screencast or provide a full log from cloning until npm start?
Also: which OS/version are you using?

**Comment by thaoredweb** [comment]
The windows 10 pro @jatitoam, I will send you an video later

**Comment by thaoredweb** [comment]
@jatitoam can you take a look at this issue? It is high severity since many users are using Windows

**Comment by jatitoam** [comment]
This is ready for testing in develop @thaoredweb @VanTrieuThanh

**Comment by jatitoam** [comment]
Hold on, I found something else

**Comment by jatitoam** [comment]
done @thaoredweb @VanTrieuThanh  this time it works in all OSs

**Comment by VanTrieuThanh** [comment]
Window - npm 14.17.3 has working cc @jatitoam , @thaoredweb

**Comment by thaoredweb** [comment]
MAC has worked with node 16.15.1 @jatitoam

**Comment by jatitoam** [comment]
I'll move this to release
