### ISSUE TITLE
Remove the message when nothing hover on field

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/dma-app#44]
1. Launch the app
2. go to sign in page
 Actual output:
 Showing the error message while do nothing with required field
 

![Image](https://user-images.githubusercontent.com/30283123/177268712-efe28817-0069-4c4a-a1cf-88b27247c0ed.png)

**Comment by jatitoam** [comment]
@GiaPhu811  there is no PR for this issue

**Comment by jatitoam** [comment]
Found the PR

**Comment by VanTrieuThanh** [comment]
it has fine for me
