### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by lunguyenhat** [aesirxio/dma-app#45]

**Comment by thaoredweb** [comment]
Besides darkmode, it is also update to lot of themes.

**Comment by jatitoam** [comment]
@thaoredweb you can test this one on the `develop-theme-multilang` branch

**Comment by thaoredweb** [comment]
@VanTrieuThanh can you help to check e

**Comment by VanTrieuThanh** [comment]
Missing custom color 
![image](https://user-images.githubusercontent.com/44457418/184064601-b588f330-20d4-4ca2-a799-a857fa02f7bc.png)
missing language 
![image](https://user-images.githubusercontent.com/44457418/184064266-810ab2e4-cc3b-4a76-a7a7-1b94189513ac.png)
change the color for placeholder 
![image](https://user-images.githubusercontent.com/44457418/184064353-7824b4f0-cd83-4e01-a5e8-0aa69be162af.png)
Dropdown year missing 
![image](https://user-images.githubusercontent.com/44457418/184064509-b522570d-7e47-4a32-bdae-78e03f28c22d.png)
sync bacground-color 
![image](https://user-images.githubusercontent.com/44457418/184064755-636721b0-b384-42a3-8217-323b04e9a721.png)
![image](https://user-images.githubusercontent.com/44457418/184064890-48f0dc2f-e6eb-44f7-b892-3937f1906554.png)
Collection Asset 
![image](https://user-images.githubusercontent.com/44457418/184064789-c26b6e33-519c-4d21-a403-0313c88cd86d.png) 
Create Post show error - but go to list the post just error has show on the list 
![image](https://user-images.githubusercontent.com/44457418/184065194-67346734-5c8d-420e-9d6a-b7c6c84a3126.png)
![image](https://user-images.githubusercontent.com/44457418/184065277-e27046f2-6e6a-4a87-b1f0-a5ed89ae562e.png)
Hide the column 
Project Hide Short description - Start date lost the background 
![image](https://user-images.githubusercontent.com/44457418/184065314-f5d496cb-c032-4183-b0cb-5b5dc3bb7cf2.png)
![image](https://user-images.githubusercontent.com/44457418/184065390-536209f0-afac-4d55-9b19-ec3267350e06.png)
Post
![image](https://user-images.githubusercontent.com/44457418/184065479-703e2288-f53d-4ffe-8a52-f4c5e473d362.png)
Campaign 
![image](https://user-images.githubusercontent.com/44457418/184065597-c2fa4f5e-9346-4224-8af0-59649b60b651.png)
Dark-light mode - missing line 
![image](https://user-images.githubusercontent.com/44457418/184065657-0a5512b8-e8c0-429d-b16d-c1daeb2cee33.png)

**Comment by jatitoam** [comment]
Back your way @VanTrieuThanh

**Comment by VanTrieuThanh** [comment]
change the color for placeholder
![image](https://user-images.githubusercontent.com/44457418/184799811-ecec7afa-e1f3-4e41-b9fb-80931035b07e.png)
Dropdown year missing (Firefox)
![image](https://user-images.githubusercontent.com/44457418/184799891-02ea3e49-9a98-47c1-9338-7339dda3539c.png)
Pagination 
![image](https://user-images.githubusercontent.com/44457418/184800139-11fdf2b0-1c7a-44ad-aa31-f0f6cd8d4d61.png)
help me fix again em ơi

**Comment by GiaPhu811** [comment]
Will be fixed on dev branch with #98 and #96, it will apply when merge with dev branch
