### ISSUE TITLE
Checkbox color & Translation for Status

### ISSUE THREAD

**Issue by GiaPhu811** [aesirxio/dma-app#473]
Checkbox don't have background when selected
![image](https://github.com/aesirxio/dma-app/assets/106291216/2ca40f14-c65a-4df9-a727-a4e635829810)

Translate for `txt_processing`
![image](https://github.com/aesirxio/dma-app/assets/106291216/51fce8c4-6d1d-4867-9415-8c3f67845fce)

**Comment by trucduy10** [comment]
![image](https://github.com/aesirxio/dma-app/assets/90845140/5e7a3bcb-8bae-4624-b946-2a8a48e7d2c7)
The checkbox's css still works normally when selected on the dma. But there was a problem on the dapp, so the css of the checkbox was overwritten

**Comment by GiaPhu811** [comment]
We have `bg-transparent` on checkbox so it make issue above please help me remove this class chị

![image](https://github.com/aesirxio/dma-app/assets/106291216/73655aba-72bb-499d-a223-7ddad96f812d)
