### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by lunguyenhat** [aesirxio/dma-app#50]

**Comment by jatitoam** [comment]
Sent your way also @thaoredweb , you can also use the `develop-theme-multilang` branch

**Comment by VanTrieuThanh** [comment]
placeholder 
![Image](https://user-images.githubusercontent.com/44457418/184067629-fbf20efb-3533-496c-8c21-a5bfbcdcbb8f.png)
Choose file 
![Image](https://user-images.githubusercontent.com/44457418/184067710-fde9996c-4262-45b4-8139-ee8a1022a6c7.png)
Profile 
![Image](https://user-images.githubusercontent.com/44457418/184067737-f5aa0589-5029-466c-af94-91fb495fc662.png)
Calendar 
![Image](https://user-images.githubusercontent.com/44457418/184067775-202233f3-f8ec-47cd-8f33-b8a9ae050877.png)
filter day
![Image](https://user-images.githubusercontent.com/44457418/184067815-b2498896-16d6-4baa-9507-4cca42b1ca1f.png)
Content 
![Image](https://user-images.githubusercontent.com/44457418/184067843-b18556ef-5763-4a07-807e-6d2205a6e342.png)
Channel 
![Image](https://user-images.githubusercontent.com/44457418/184067889-4e3e06fb-5900-426c-a466-882e5cd13ddf.png)

**Comment by jatitoam** [comment]
@toanredweb can you please check these?

**Comment by VanTrieuThanh** [comment]
Profile not fix em ơi 
![image](https://user-images.githubusercontent.com/44457418/185839295-3c0c62b1-025b-436b-8ad3-534e10a9491c.png)
Calendar 
![image](https://user-images.githubusercontent.com/44457418/185839657-72091a82-e8cd-422d-a9fe-267d9c5f592b.png)
![image](https://user-images.githubusercontent.com/44457418/185840384-946b97d9-1561-4832-b1c9-88bb1c2deebf.png)
Project 
![image](https://user-images.githubusercontent.com/44457418/185840446-b104ea56-8dc8-4e9d-abaf-d1866cb6845e.png)
Select Ukraina language and logout app then login again - Language auto change is English but title still show on Ukraina
![image](https://user-images.githubusercontent.com/44457418/185839920-efa45f42-b56b-41f8-8811-3364df2fb7cd.png)
Select Denmark language and reload page - Language, title auto change is English 
Campaign 
![image](https://user-images.githubusercontent.com/44457418/185841288-29b79a46-9dff-496b-ad18-e0b9a282cb31.png)

Content 
![image](https://user-images.githubusercontent.com/44457418/185840346-e27f4505-3a4d-415c-8011-96e54922d745.png)
Button 
![image](https://user-images.githubusercontent.com/44457418/185841113-32375962-aee5-4d68-b8a5-2cc9622edc2e.png)
Step 2 
![image](https://user-images.githubusercontent.com/44457418/185841174-a1f5c895-2eaf-4737-b42d-b4141e6cf22d.png)

**Comment by VanTrieuThanh** [comment]
1. + more 
![image](https://user-images.githubusercontent.com/44457418/186068677-508de84d-0327-499d-bcbb-44fe198039df.png)
2. date on the calendar 
![image](https://user-images.githubusercontent.com/44457418/186068729-56efb4d0-22d3-41f2-b816-175ededc15e4.png)
![image](https://user-images.githubusercontent.com/44457418/186068751-6c39861c-b92f-4f7d-8a39-f4659ab977be.png)
3. Reload page auto switch EN language 
![image](https://user-images.githubusercontent.com/44457418/186068863-6ccdb0be-e31a-4921-acc8-26e1171c2e3f.png)

**Comment by jatitoam** [comment]
@toanredweb  please remember this one

**Comment by VanTrieuThanh** [comment]
Calendar has changed language and more has fixed 
![image](https://user-images.githubusercontent.com/44457418/186303861-e71b4cab-4849-4bde-ab56-d723000172be.png)
![image](https://user-images.githubusercontent.com/44457418/186303900-173fce56-0e26-4ddf-ab1a-2f88cd5d5cc8.png)
