### ISSUE TITLE
Tag not show all info

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/dma-app#51]

**Comment by toanredweb** [comment]
@jatitoam This issue has been fixed before

**Comment by jatitoam** [comment]
do you have the other task?

**Comment by toanredweb** [comment]
I have

**Comment by jatitoam** [comment]
Can you please send it? :)

**Comment by toanredweb** [comment]
@jatitoam  It here https://github.com/aesirxio/dma-app/pull/38

**Comment by VanTrieuThanh** [comment]
the filter day it has show full but it not good for layout if the time have many item post 
![image](https://user-images.githubusercontent.com/44457418/185545949-9d1cf94d-5801-4f64-bcce-e3eab1ab2a50.png)
the filter week it not good em ơi 
![image](https://user-images.githubusercontent.com/44457418/185546078-672fb93c-2348-4c93-94e8-b73338b10e03.png)

**Comment by VanTrieuThanh** [comment]
View week 
![image](https://user-images.githubusercontent.com/44457418/185837014-2b3ec6db-1857-4f02-bfa6-3e2c963d4a5c.png)
View day 
![image](https://user-images.githubusercontent.com/44457418/185837209-715f0bd9-3262-41ce-ba91-a79b265fb626.png)
the something went error has fixed
