### ISSUE TITLE
Post/Campaign -Date field-highlight the range select

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/dma-app#53]

**Comment by VanTrieuThanh** [comment]
![image](https://user-images.githubusercontent.com/44457418/178397381-77ecd20e-b6ea-46f0-928e-49e2b3243941.png)

**Comment by VanTrieuThanh** [comment]
@toanredweb oi help me check again the action select date, each select the field date is hiden you can check video. http://recordit.co/uy3JmYuoHy
the highlight has working on

**Comment by VanTrieuThanh** [comment]
it has fine for me on the latest version http://recordit.co/5s2kfSWIR1
