### ISSUE TITLE
Error on upload image in Profile

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/dma-app#55]
1. Login to app at local
2. Go to Profile page and change the avatar
3. Upload a new file image 
Actual output:
Show errors on the page. In fact, it is uploading the image but nothing shows ít progress

![Image](https://user-images.githubusercontent.com/30283123/178688552-8728b20e-548e-49ab-bf49-56c47a14c4dc.png)

**Comment by NguyenBao10** [comment]
please check again chi @thaoredweb

**Comment by huynhngocgiau** [comment]
1. Empty message when upload file is successful
![message](https://user-images.githubusercontent.com/79819354/215739891-9b11afa8-8043-49b1-a6bb-69204fe451d5.png)

2. Can't update profile picture
![saveprofile](https://user-images.githubusercontent.com/79819354/215740077-976b4151-375a-4d71-8964-c3c5d5e40115.png)

**Comment by CongThuong** [comment]
I've checked on my local (dev) and demo-app (live) the API to update Avatart works normally, Please take a look again Chi @thaoredweb  Em @huynhngocgiau 

![image](https://user-images.githubusercontent.com/94885770/217994859-3d19b6af-0441-47d9-adc0-02627c96f8d6.png)

**Comment by thaoredweb** [comment]
@GiaPhu811 the issue need support from FE so let a look e
