### ISSUE TITLE
App require user login to joomla app

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/dma-app#56]
1. Launch app at local
2. Login with your user
3. Go to Digital Asset, click on New
Actual output:
It requires login to joomla

![Image](https://user-images.githubusercontent.com/30283123/178699554-bc4d2c53-72db-407d-b8ea-1d8ea4541b66.png)

**Comment by NguyenBao10** [comment]
pleas check again chi @thaoredweb

**Comment by VanTrieuThanh** [comment]
layout new has show on the app on my local on the endpoint live site 
![image](https://user-images.githubusercontent.com/44457418/215972193-24395af4-c541-4e1d-b1d6-5870e16dec12.png)
