### ISSUE TITLE
Can not search at Content page/Projects

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/dma-app#59]
1. Lauch the app
2. Login to success and go to Content page
3. Create a post success
4. Search with tile of post 
 Actual output:
When user click on enter or search icon. It does not work

**Comment by jatitoam** [comment]
@GiaPhu811 there is no PR for this issue

**Comment by jatitoam** [comment]
Found the PR

**Comment by VanTrieuThanh** [comment]
it has fine for me
