### ISSUE TITLE
Calendar - Filter not fine

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/dma-app#60]
1 click on item Kontormoebler → show tick on Sofacompany

2 Can’t unselect the item just click 

3 After click “Select all“ it should be change to “Deselect all“

4 “Clear All” not working 

http://recordit.co/LXHtXjJPzw

Actual output:
Sometime click to desect on checkbox but it dont work

**Comment by jatitoam** [comment]
@GiaPhu811 there is no PR for this issue

**Comment by VanTrieuThanh** [comment]
it has fine for me http://recordit.co/nWmod3ldIz
