### ISSUE TITLE
Limit posts from API according to package limit

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/dma-app#61]
According to the new package limit set in [AESX-1: Add tracking data for posts per day and DAM storage to the Package content typeDONE](https://redweb.atlassian.net/browse/AESX-1) posts (type “Posts”) should be limited daily when coming from the API for a particular user.

**Comment by NguyenBao10** [comment]
it's limited, please check again chi @thaoredweb

**Comment by thaoredweb** [comment]
@NguyenBao10 I limited the post to 3 but I can post 5 post a day. please check again e
