### ISSUE TITLE
[Digital Asset] Broken title on DAM

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/dma-app#62]
Upload a image that the title is too long

![Image](https://user-images.githubusercontent.com/30283123/178950181-70fda1d1-fa8f-441c-aec5-5e44cb20250f.png)

**Comment by NguyenBao10** [comment]
please check again chi @thaoredweb

**Comment by VanTrieuThanh** [comment]
it has change to "..." with the title too long
![image](https://user-images.githubusercontent.com/44457418/215974047-68fd1b26-af4a-43db-b896-8f73455dba08.png)
