### ISSUE TITLE
Can not search on Digital Assets

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/dma-app#63]
1. launch the app
2. Go to Digital Asset
3. Search with title of images
Actual output: 
Show login to joomla page 

![Image](https://user-images.githubusercontent.com/30283123/178953242-4bb5b69a-21d5-48c3-b6cc-6e240584ae79.png)

**Comment by NguyenBao10** [comment]
we integrated DAM for Digital Assets, please check again chi @thaoredweb

**Comment by VanTrieuThanh** [comment]
the search on Digital Assets has remove on DMA 
![image](https://user-images.githubusercontent.com/44457418/215973420-e96594d2-49ab-46d1-89d6-e452e1c49ffb.png)
