### ISSUE TITLE
The password fields should be hiden

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/dma-app#65]
The password should be hiden ( enables user to view if need)

![Image](https://user-images.githubusercontent.com/30283123/178954903-280e96e6-3d06-45c1-9ecb-08638b9759eb.png)

**Comment by jatitoam** [comment]
@GiaPhu811 there is no PR for this issue

**Comment by jatitoam** [comment]
Found the PR

**Comment by VanTrieuThanh** [comment]
it has encryption for password
![image](https://user-images.githubusercontent.com/44457418/183819031-28b24de8-631b-4770-950c-5e21da6d3ff2.png)
