### ISSUE TITLE
Merge all posts into one when they have the same time range

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/dma-app#66]
1. Launch the app
2. Create some posts that the time closely together.
3. Go to Calendar and filter with Week

Actual output:

![Image](https://user-images.githubusercontent.com/30283123/178957444-95e31443-1616-4caf-be57-c50dc023afed.png)

Expected output:
Show alll of them in only one tag

**Comment by toanredweb** [comment]
This issues is not supported by the library  cc a @lunguyenhat

**Comment by NguyenBao10** [comment]
just to confirm, this issue dont need BE, right e @toanredweb @GiaPhu811 ?

**Comment by GiaPhu811** [comment]
Yes a @NguyenBao10, because library not support so we can't merge event together
