### ISSUE TITLE
Can not remove the image

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/dma-app#67]
Can not remove the image, please check the download and edit the image as well
![Image](https://user-images.githubusercontent.com/30283123/178963837-4bdfb183-879d-4065-a1bc-b557b02c40f1.png)

**Comment by NguyenBao10** [comment]
i see they are fine, please check again chi @thaoredweb

**Comment by VanTrieuThanh** [comment]
the image has remove but the message it not show the text
![image](https://user-images.githubusercontent.com/44457418/215976522-cee5929e-bea4-45dc-8c8b-7af79c805c67.png)

**Comment by toanredweb** [comment]
Api  not working  a @NguyenBao10 

![Image](https://user-images.githubusercontent.com/70501609/217189203-9a859edb-1b97-46c7-aa2f-7c5a7b7d33df.png)

**Comment by CongThuong** [comment]
I've just checked and see Delete API that works both collection and asset on Demo-App
please take a look again Chi @VanTrieuThanh, Em @toanredweb 

![image](https://user-images.githubusercontent.com/94885770/217992767-31785a19-526d-4386-84f0-6f71a897c3b5.png)
![image](https://user-images.githubusercontent.com/94885770/217992804-dd9b640f-9742-4a0f-b1f3-c117db461eed.png)

**Comment by CongThuong** [comment]
On Admin - product-aesirx-dam_community_demo-dma. I can delete asset as well

![image](https://user-images.githubusercontent.com/94885770/217993288-9c8679d1-78de-4963-a4a0-a914765b4a2f.png)

**Comment by huynhngocgiau** [comment]
worked
![image](https://user-images.githubusercontent.com/79819354/218373218-7458a8c8-3532-4248-a75b-0a51f41d7ac6.png)
