### ISSUE TITLE
Content - Status post content (schedule) not post over time

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#69]
I create the Post have schedule post is 3:15 at Jul 15, 2022
but when 3:39 I comeback at list the post still status schedule 
![Image](https://user-images.githubusercontent.com/44457418/179186801-bd05a83a-947f-4b28-aeb2-d48dbf38fb33.png)
and go to the detail the time showing is current time 
![Image](https://user-images.githubusercontent.com/44457418/179187597-0430df8b-4468-4c6b-830c-b2cda25461f3.png)

**Comment by anhtuan2588** [comment]
@GiaPhu811 check this issue, please

**Comment by toanredweb** [comment]
I thought it was an API bug but now it working cc chị @VanTrieuThanh

**Comment by toanredweb** [comment]
![Screenshot from 2022-10-24 16-13-10](https://user-images.githubusercontent.com/70501609/197491695-2d895634-ce83-498d-838e-e607aa59380b.png)

**Comment by VanTrieuThanh** [comment]
it still not post em ơi and the time incorrect 
![image](https://user-images.githubusercontent.com/44457418/199649969-f4ff9d71-87bb-4a3b-92bd-d010f35c74f0.png)

**Comment by toanredweb** [comment]
Pls help me check API of this issues  a @NguyenBao10

**Comment by CongThuong** [comment]
This task is related to https://gitlab.redweb.dk/aesirx/aesir-webservice/-/issues/82. QA status now

**Comment by CongThuong** [comment]
This task is related to https://gitlab.redweb.dk/aesirx/aesir-webservice/-/issues/82, QA status now

**Comment by VanTrieuThanh** [comment]
Can't connect channel. I will check when the task https://github.com/aesirxio/dma-app/issues/211 is fixed

**Comment by CongThuong** [comment]
Maybe you have not configed the aesir-webservice to use local laravel. The schedule (queue) is no longer available on this https://service.r.redweb.digital  . Chi @thaoredweb cc Anh @NguyenBao10 
![image](https://user-images.githubusercontent.com/94885770/217996766-c4975142-9dc2-450d-a512-7bbcbb9b66c3.png)

**Comment by VanTrieuThanh** [comment]
Just create the post with content 
![image](https://user-images.githubusercontent.com/44457418/220025108-93999b33-04a3-49cf-8d4c-3af4496db409.png)
The medium not post the with schedule 
![Screenshot from 2023-02-20 13-26-01](https://user-images.githubusercontent.com/44457418/220028490-517c7298-fcd1-47b3-b904-4efbb242c9c9.png)

**Comment by toanredweb** [comment]
Pls help me check task e @nhatvippro
