### ISSUE TITLE
Channel - Message connect successfully has duplicate

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#70]
![Image](https://user-images.githubusercontent.com/44457418/179192173-30063d1b-9722-48d4-97b0-9391621eba7a.png)

**Comment by VanTrieuThanh** [comment]
https://recordit.co/uOCrYFHjUQ look like it duplicate after I login the second, third .... time @GiaPhu811

**Comment by jatitoam** [comment]
@GiaPhu811 there is no PR for this issue

**Comment by jatitoam** [comment]
Found the PR

**Comment by VanTrieuThanh** [comment]
it has remove the duplicate message after logout and Connect channel again
