### ISSUE TITLE
Content - Status posts has posted not change on list

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#71]
Content list 
![Image](https://user-images.githubusercontent.com/44457418/179192969-f1a9b6c9-cb7d-4568-9cd8-927cb82efbcb.png)
Content Detail 
![Image](https://user-images.githubusercontent.com/44457418/179192744-24f1e0d7-6498-4e91-a490-9b76f170044d.png)
Fanpage 
![Image](https://user-images.githubusercontent.com/44457418/179192811-c2a66b67-1f80-431d-8abf-df1cd1cd6eb8.png)

**Comment by CongThuong** [comment]
please lemme know which branch or site you testing? Chi @VanTrieuThanh

**Comment by CongThuong** [comment]
I've just checked the wordpress Channel on dev-branch and see the label is working 

![image](https://user-images.githubusercontent.com/94885770/215698621-98fed691-68fd-4458-a4b3-117e139c0cac.png)

**Comment by CongThuong** [comment]
I've just checked the joomla3 Channel (old Queue) via laravel on dev-branch and see the label is working


![image](https://user-images.githubusercontent.com/94885770/215714323-d98c002a-d52b-4981-a73b-8830463e7997.png)

**Comment by VanTrieuThanh** [comment]
the Post has upload on the Medium 
![image](https://user-images.githubusercontent.com/44457418/220013137-70e6c857-dc36-42a5-889a-28d6e388a4e6.png)
but it item on app it not update status 
![image](https://user-images.githubusercontent.com/44457418/220013189-44ffaafe-3bfa-46b2-ab0a-0ede320dc4fa.png)
