### ISSUE TITLE
[Calendar] Agenda filter does not work

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#72]
![image](https://user-images.githubusercontent.com/44457418/179203095-852b39d6-47eb-481b-bf4a-dcc07908af30.png)
Actually, I have a post in 26-May

**Comment by GiaPhu811** [comment]
I fixed it on [PR-41](https://github.com/aesirxio/dma-app/pull/41)

**Comment by jatitoam** [comment]
@GiaPhu811 there is no PR for this issue

**Comment by jatitoam** [comment]
Found the PR

**Comment by VanTrieuThanh** [comment]
it has fine for me 
![image](https://user-images.githubusercontent.com/44457418/183843430-b7985703-499d-47cf-8ab6-17345b04704e.png)
