### ISSUE TITLE
Profile - Not show year when user click on the dropdown list icon

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#75]
User click on the dropdown icon in date 
![Image](https://user-images.githubusercontent.com/44457418/179483032-2c397c13-38a4-4e9a-a15f-d9fbf841bef1.png)
Actual result : Not show year in field ![Image](https://user-images.githubusercontent.com/44457418/179482968-a51a599a-0f2d-4627-9395-057b265c32d6.png)

**Comment by jatitoam** [comment]
@GiaPhu811 there is no PR for this issue

**Comment by jatitoam** [comment]
Found the PR

**Comment by VanTrieuThanh** [comment]
@GiaPhu811 help me check again em ơi 
![image](https://user-images.githubusercontent.com/44457418/183843568-b6813b6b-a84f-42e0-9663-54b22c37c57a.png)

**Comment by jatitoam** [comment]
back to you @VanTrieuThanh

**Comment by VanTrieuThanh** [comment]
it has fine for me on the demo app.
