### ISSUE TITLE
Profile - Avatar in top right hasn't update

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#76]
Update successful avatar in profile page 
![Image](https://user-images.githubusercontent.com/44457418/179483883-9ebacb31-6ac0-47c3-93d2-38e39a793c24.png)
Actual result : the icon avatar in top right not update 
![Image](https://user-images.githubusercontent.com/44457418/179484100-ecd84023-f243-4faa-9775-b5debbf30a2e.png)
Version 1.3.3-alpha.1

**Comment by jatitoam** [comment]
@GiaPhu811 there is no PR for this issue

**Comment by jatitoam** [comment]
Found the PR

**Comment by VanTrieuThanh** [comment]
it has updated after change the avatar 
![image](https://user-images.githubusercontent.com/44457418/183831166-af0bcb8a-8e81-4a9b-b2d3-a22c43a29084.png)
