### ISSUE TITLE
Loading icon - should be center the content page

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#81]
![Image](https://user-images.githubusercontent.com/44457418/181415948-2679f07d-0a0b-4f73-81a2-1c2b199bbed0.png)

**Comment by jatitoam** [comment]
@GiaPhu811  there is no PR for this issue

**Comment by VanTrieuThanh** [comment]
it has fine for me http://recordit.co/H7RSquW0RD
