### ISSUE TITLE
Post - Something went wrong when select the Advance mode

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#82]
User create 1 post item and turn on the Advance mode 
Create successful the post 
Then click to view detail the post just create 
Click on the "Next" button 
Actual result: Webpage show the "Something went wrong"
 http://recordit.co/bYoemt5His

**Comment by jatitoam** [comment]
@GiaPhu811 there is no PR for this issue

**Comment by jatitoam** [comment]
Found the PR

**Comment by VanTrieuThanh** [comment]
it has fine for me http://recordit.co/3djzdj7h8u
