### ISSUE TITLE
Easy creation of custom logo

### ISSUE THREAD

**Issue by lunguyenhat** [aesirxio/dma-app#87]

**Comment by jatitoam** [comment]
@toanredweb @anhtuan2588 I don't see any PR here?

**Comment by jatitoam** [comment]
Found it https://github.com/aesirxio/dma-app/pull/110

**Comment by VanTrieuThanh** [comment]
Not complete

**Comment by jatitoam** [comment]
Backend support was missing, can you please check again?

**Comment by VanTrieuThanh** [comment]
1 I has update logo it has update to Profile 
2 The logo image in field not keep image select - it return the image first 
![image](https://user-images.githubusercontent.com/44457418/193220177-a21ae024-8972-4991-8f31-41431000a0dd.png)
