### ISSUE TITLE
Content - Can't delete the content item

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#88]
Select item want to delete 
![Image](https://user-images.githubusercontent.com/44457418/182511284-233b47ee-bab0-4e9e-93c0-55afa35279d9.png)
Choose the OK 
![Image](https://user-images.githubusercontent.com/44457418/182511376-b94c9328-685c-4c52-b37f-e3fba8f5bf85.png)
App loading overtime 
![Image](https://user-images.githubusercontent.com/44457418/182511483-fda2f000-574c-45dc-9bc0-54d9c98f27b6.png)

**Comment by anhtuan2588** [comment]
this issue can resolve by change webservices -> "DMA AesirX - Content" -> content -> delete -> fields -> ids from JSON format come array format

**Comment by GiaPhu811** [comment]
I can't delete multiple content when i use array as parameters. Result : true, but content not delete. @anhtuan2588 

![Image](https://user-images.githubusercontent.com/106291216/192483752-d6ba259c-e213-4611-bcec-7d010d1a8ac4.png)

![Image](https://user-images.githubusercontent.com/106291216/192483843-a50ec223-7d32-494a-947e-5c14ba9bf315.png)

**Comment by jatitoam** [comment]
Reported in backend API call

**Comment by NguyenBao10** [comment]
![image](https://user-images.githubusercontent.com/34084070/197451688-55fb316c-dd4f-4c5e-b6f2-3be50d3208f6.png)
"ids" params should be inputed like this e @GiaPhu811

**Comment by GiaPhu811** [comment]
We use object to make url, object can't have same key so we can't do like image. Can we send it with formdata ? @NguyenBao10

**Comment by CongThuong** [comment]
The old code is working normally if using form-data, Nothing needs to change in backend. please recheck Em @GiaPhu811

**Comment by VanTrieuThanh** [comment]
the Content has remove item delete
