### ISSUE TITLE
Content - The post select Publish is Schedule save the time create

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#90]
Create new content ![Image](https://user-images.githubusercontent.com/44457418/183809240-a5506e57-fe04-49dc-a090-d7d372c7d899.png)
Select the time post 
![Image](https://user-images.githubusercontent.com/44457418/183809261-9ff82acf-c71d-4141-bca6-253b2754c43c.png)
The Date in list content show created time 
![Image](https://user-images.githubusercontent.com/44457418/183809281-aaad1434-96bc-465f-9d25-82df0fc39a23.png)
Detail content show current time 
![Image](https://user-images.githubusercontent.com/44457418/183809548-b8fad97e-c622-40e1-9be3-7d367d586c6f.png)
Expected result : Detail content the time it should be display time user has selected create before 
The time it has effect Calendar the time in Calendar should be show the time post 
![Image](https://user-images.githubusercontent.com/44457418/183810166-3c351083-b218-4917-a952-fc47001ebe9c.png)

**Comment by anhtuan2588** [comment]
This issue should use time from database (not use current time when show at frontend)

**Comment by CongThuong** [comment]
This task is related to https://gitlab.redweb.dk/aesirx/aesir-webservice/-/issues/82.  QA status now

**Comment by GiaPhu811** [comment]
It's because front end show wrong date. I'm checking a @CongThuong

**Comment by VanTrieuThanh** [comment]
I has create 1 post but when I click to view detail it not show detail - it loading overtime
![image](https://user-images.githubusercontent.com/44457418/220035124-fe5c30a8-1f41-4630-926c-b50dbfcaa9e6.png)

**Comment by toanredweb** [comment]
Pls help me check task e @nhatvippro

**Comment by nhatvippro** [comment]
![image (2)](https://user-images.githubusercontent.com/117979505/224246899-63bffab7-2459-4819-9265-5d1de6246f97.png)
![image (1)](https://user-images.githubusercontent.com/117979505/224246942-08b5dfed-6c40-430b-a5e4-d7e234e25aad.png)
![image](https://user-images.githubusercontent.com/117979505/224246969-3fe94146-143e-4b7e-b3b2-ecdab37b8528.png)
api still fine, pls double check a @toanredweb

**Comment by nhatvippro** [comment]
![image (2)](https://user-images.githubusercontent.com/117979505/224247554-92a87b9d-8f4f-44f4-b871-48dc1ac87c5b.png)
![image (1)](https://user-images.githubusercontent.com/117979505/224247470-b3b07314-d8b4-4b13-8d10-a02a4b19a8ba.png)
![image](https://user-images.githubusercontent.com/117979505/224247541-182030e4-125f-4279-a1ee-ba0a31811958.png)
api still fine, pls double check a @toanredweb

**Comment by toanredweb** [comment]
please pull PR https://github.com/aesirxio/dma-app/pull/282 to check chị @VanTrieuThanh

**Comment by VanTrieuThanh** [comment]
Can't connect channel - BE is fixing
