### ISSUE TITLE
Create Post - Show "Something was wrong. Please try again"

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/dma-app#93]
Create Post show error - but go to list the post just error has show on the list 
![image](https://user-images.githubusercontent.com/44457418/184065194-67346734-5c8d-420e-9d6a-b7c6c84a3126.png)
![image](https://user-images.githubusercontent.com/44457418/184065277-e27046f2-6e6a-4a87-b1f0-a5ed89ae562e.png)

**Comment by anhtuan2588** [comment]
can't find this bug

**Comment by jatitoam** [comment]
@VanTrieuThanh can you please confirm this one or close it?

**Comment by VanTrieuThanh** [comment]
I has try reproduce but it not display error

**Comment by jatitoam** [comment]
Ok, then I'll close it.  Thanks.
